### ISSUE TITLE
能否直接获取指定群的消息

### ISSUE THREAD

**Issue by gyje** [nonebot/python-cqhttp#1]
@bot.on_message()
是获取所有的消息，有没有API获取指定群消息
文档能不能再完善一下，Thanks

**Comment by stdrc** [comment]
目前不能指定群，但可以指定获取群消息，比如：

```py
@bot.on_message('group')
def handle_group_msg(context):
    print(context['group_id'])  # 获取群号
    return {'reply': '回复'}
```

这里的 `context` 是个 dict，内容就是 [这里](https://richardchien.github.io/coolq-http-api/#/Post?id=%E4%BA%8B%E4%BB%B6%E5%88%97%E8%A1%A8) 的「上报数据」。

`on_message` 的参数，就是指定 `message_type`。

这个当时写得比较匆忙，功能也并不多，所以没太把文档写详细，等后面有空我会完善一下。

更多时候你其实需要参考 [事件上报](https://richardchien.github.io/coolq-http-api/#/Post) 和 [API 描述](https://richardchien.github.io/coolq-http-api/#/API)。
