### ISSUE TITLE
机器人无法匿名发消息

### ISSUE THREAD

**Issue by 625781186** [nonebot/python-cqhttp#11]
```
if str(user_id) == "943359205":
    ...
elif str(user_id) == "80000000":
    return bot.send(context,
                    message="""[CQ:anonymous,ignore=true] , 匿名清屏."""))
```
群是支持 匿名的 ， 机器人可以发出消息来 ，但不是匿名发送.

**Comment by richardchien** [comment]
试试手动登录机器人的 QQ 看能不能发送匿名消息？（在真的 QQ 里面

**Comment by stdrc** [comment]
发出来的消息内容就是单纯的 `匿名清屏`？

**Comment by stdrc** [comment]
试试手动登录机器人的 QQ 看能不能发送匿名消息？（在真的 QQ 里面

**Comment by 625781186** [comment]
> 试试手动登录机器人的 QQ 看能不能发送匿名消息？（在真的 QQ 里面

手动登录可以发 , 只是用匿名发一段文字 
![image](https://user-images.githubusercontent.com/30521429/46572422-0469ad00-c9b8-11e8-8389-1bc1f494f4b0.png)

![image](https://user-images.githubusercontent.com/30521429/46572454-56aace00-c9b8-11e8-8679-be790baf5406.png)

**Comment by stdrc** [comment]
哦对，我想起来了，你应该是酷 Q Air 吧，这可能是个 Pro 特性（
