### ISSUE TITLE
使用cqhttp_helper.py后调用.send()后报错

### ISSUE THREAD

**Issue by winrey** [nonebot/python-cqhttp#14]
因为cqhttp的send()会调用self.send_msg(**context)，但是cqhttp_helper.py中的CQHttp中具体实现了send_msg()方法，并且规定了参数，但context中存在没有该方法的参数，如font等，因此调用send会报错

**Comment by stdrc** [comment]
@remini1998 现在不太建议用那个 helper 了

**Comment by winrey** [comment]
> @remini1998 现在不太建议用那个 helper 了
回复好快，不过我提issue的时候就都顺手修完了……

**Comment by stdrc** [comment]
@remini1998 因为我是在 telegram 直接回的（

**Comment by stdrc** [comment]
@remini1998 你的 PR 看到了，等下处理

**Comment by winrey** [comment]
@richardchien 哇，这个操作棒
