### ISSUE TITLE
新人入群如何@并发送欢迎消息？

### ISSUE THREAD

**Issue by jiangjiangflies** [nonebot/python-cqhttp#16]
您好！
在新增群成员事件中：
bot.send(context, message='欢迎新人～', auto_escape=True)  # 发送欢迎新人
如何同时@新人呢？或者说，如何@指定的QQ号呢？
谢谢！

**Comment by kj415j45** [comment]
@jiangjiangflies [CQ:at,qq=123456789]
具体请看 CQHTTP 的 CQ码 页

**Comment by richardchien** [comment]
@jiangjiangflies 现在可以直接给 send() 加 at_sender=True 参数

**Comment by stdrc** [comment]
可以在 message 开头加上 `[CQ:at,qq=12345678]`（[CQ 码](https://cqhttp.cc/docs/#/CQCode)），但这样的话需要把 `auto_escape` 置为 `False`

**Comment by jiangjiangflies** [comment]
成功了~ 谢谢大佬指点~
