### ISSUE TITLE
使用问题 我需要怎么做监听一个正则信息？

### ISSUE THREAD

**Issue by nu1ee** [nonebot/python-cqhttp#18]
http api
``{
    "host": "127.0.0.1",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "",
    "ws_reverse_event_url": "",
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": true,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "github",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": false,
    "log_level": "info"
}``

``from cqhttp import CQHttp, Error

bot = CQHttp(api_root='http://127.0.0.1:5700/')

@bot.on_message()
def handle_msg(context):
	print(context['message'])

bot.run(host='127.0.0.1', port=8080)``

打印收到的信息 运行起来没有反应的？ 是我哪里配置错了？
`` * Serving Flask app "cqhttp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
``

**Comment by stdrc** [comment]
CoolQ HTTP API 插件的配置里面需要填写 `post_url`，具体建议详细看下本项目的 README
