### ISSUE TITLE
发送图片尺寸问题

### ISSUE THREAD

**Issue by miRemid** [nonebot/python-cqhttp#19]
用的酷QPro，请问如何发送原图(大图)啊，直接发出去是空的。。

**Comment by stdrc** [comment]
酷Q 日志怎么说

**Comment by miRemid** [comment]
机器人跑在docker里，日志文件要如何查看？

**Comment by stdrc** [comment]
酷Q 日志在 noVNC 可以查看，右击悬浮窗

**Comment by miRemid** [comment]
日志显示没有Error和Warn，发送大图出去只收到了文字而没有图像

**Comment by miRemid** [comment]
仔细看了下日志，提示大尺寸图片不是有效的文件

**Comment by stdrc** [comment]
图片有多大呢，可以发到附件我测试一下吗

**Comment by miRemid** [comment]
发送的url图片，例如https://i.pximg.net/c/600x1200_90_webp/imgmaster/img/2019/05/05/00/38/50/74563380_p0_master1200.jpg
发送的消息为![image](https://i.loli.net/2019/05/08/5cd1ad7b9cd1c.png)
酷Q日志![image](https://i.loli.net/2019/05/08/5cd1ad7b927a7.jpg)

**Comment by kj415j45** [comment]
`c/600x1200_90_webp/imgmaster` 并不是原图，且其实际格式为 `WebP`，酷Q目前无法直接处理该格式为QQ可接受的格式，所以发送失败。
原图是 `original (img-original)` （即 https://i.pximg.net/img-original/img/2019/05/05/00/38/50/74563380_p0.jpg ）但是并不推荐，因为原图很容易因为太大无法发送。
建议使用 `regular (img-master)` （即 https://i.pximg.net/img-master/img/2019/05/05/00/38/50/74563380_p0_master1200.jpg ），尺寸一般不会超过 1MB 因而发送成功率较高。

相关源码可参考 https://github.com/kjBot-Modules/pixiv

**Comment by miRemid** [comment]
谢谢kj，已经解决了这个问题了
但是又发现新问题，bot获取不到群组列表了，返回的列表是空值，这应该怎么办

**Comment by miRemid** [comment]
我发现重新登录就可以了，谢谢作者和kj帮助
