### ISSUE TITLE
context 如何获取群号

### ISSUE THREAD

**Issue by jiangjiangflies** [nonebot/python-cqhttp#20]
你好，
在处理context的时候，如何获取所在群的群号？
context['user_id'] 可以获得QQ号，
但是context['group_id']就会报错KeyError: 'group_id'
谢谢~

**Comment by jiangjiangflies** [comment]
奇怪，又可以了，不知道刚刚什么邪乎。。。抱歉，打扰啦。

**Comment by miranquil** [comment]
只有*确定是群消息*的时候再用 `context['group_id']`，其他的时候 `context`  字典中没有 `group_id` 这个键，因此会报错 `KeyError`。建议在不确定的时候使用如下代码：
```python
group_id = context.get('user_id')
if not group_id:
```

**Comment by jiangjiangflies** [comment]
原来如此！明白了，感谢大佬~
