### ISSUE TITLE
酷Q pro在安装http的应用的时候返回状态-103是怎么回事呀

### ISSUE THREAD

**Issue by 41xu** [nonebot/python-cqhttp#21]

**Comment by stdrc** [comment]
@41xu 可能没装 vc++ 运行库，看看 cqhttp 插件文档首页的“手动安装”那块

**Comment by 41xu** [comment]
啊不好意思我对酷Q还不太熟，文档也没仔细看昨晚，现在解决啦！谢谢大哥！

**Comment by ExerciseBook** [comment]
@41xu 一时半会儿我也忘了-103是啥了。看一下酷Q日志，那里有中文解释。
