### ISSUE TITLE
HTTP上报地址无法访问

### ISSUE THREAD

**Issue by NoneShell** [nonebot/python-cqhttp#22]
环境
- MacOS
- Docker 19.03.0
- Python3.7
问题描述
使用的docker,报错HTTP 上报地址 http://127.0.0.1:8080无法访问
尝试措施:
1. 以为是post_url的配置不正确,使用docker命令输入的参数作为环境变量
`docker run -ti --rm --name cqhttp-test \
             -v $(pwd)/coolq:/home/user/coolq \
             -p 9000:9000 \
             -p 5700:5700 \
             -p 8080:8080 \
             -e FORCE_ENV=true \
             -e COOLQ_ACCOUNT=1549894933 \
             -e CQHTTP_POST_URL=http://127.0.0.1:8080 \
             -e CQHTTP_SERVE_DATA_FILES=yes \richardchien/cqhttp:latest`
2. 如1,以为是docker不能访问容器内部,于是绑定了端口8080
3. postman对本地8080端口发包是有作用的,状态码500

**Comment by stdrc** [comment]
HTTP 上报是 docker 容器内的插件往 post_url 上报，如果你的 HTTP 后端是运行在宿主机的，需要使用 host.docker.internal 作为 host

**Comment by stdrc** [comment]
具体可以去搜索一下如何在 docker 容器内访问宿主机的端口
