### ISSUE TITLE
get_image这个是不是用不了

### ISSUE THREAD

**Issue by pasiiww** [nonebot/python-cqhttp#26]
并没有返回东西

**Comment by stdrc** [comment]
这个 API 是 酷Q 提供的 API，是用来从腾讯服务器下载图片到 酷Q `data/image` 目录的，不会传送到 Python 这边

**Comment by pasiiww** [comment]
> 这个 API 是 酷Q 提供的 API，是用来从腾讯服务器下载图片到 酷Q `data/image` 目录的，不会传送到 Python 这边

按理说调用后应该下载图片到本地然后返回path 但是我试了下好像没有?

**Comment by stdrc** [comment]
我这边测试没有问题，先 close 了，如果有进一步信息再 reopen

![1I6MF) 4WS@NY~0F)W3%)P5](https://user-images.githubusercontent.com/5317095/76768996-cdb3db00-67d6-11ea-942f-b16158d4f91e.png)

**Comment by pasiiww** [comment]
> 我这边测试没有问题，先 close 了，如果有进一步信息再 reopen
> 
> ![1I6MF) 4WS@NY~0F)W3%)P5](https://user-images.githubusercontent.com/5317095/76768996-cdb3db00-67d6-11ea-942f-b16158d4f91e.png)

我发现原因了 不知道是腾讯还是酷Q的原因部分图返回的状态是200+102

**Comment by stdrc** [comment]
102 是酷Q返回的数据有问题，不妨清下酷Q缓存，重启试试
