### ISSUE TITLE
无法收取到消息，但能够正常发出消息。撤回功能存在问题。

### ISSUE THREAD

**Issue by SuperMarioSF** [nonebot/python-cqhttp#3]
## 运行环境
HTTP API release 3.3.5 
运行于 酷Q Pro 5.11.4 (180106)
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32)
HTTP API Python SDK 版本 1.1.0 (来自pip安装)
bottle 版本 0.12.13 (来自pip安装)
requests 版本 2.18.3 (来自pip安装)

## 症状
通过`bot.on_message()`装饰器绑定了处理函数，但这个处理函数始终都没有被调用过。从酷Q的日志里能看到酷Q收到了消息。测试的消息由群消息和私聊消息。
项目自带的`demo.py`也未能正常工作。

但发消息的部分正常工作。只是撤回消息时遇到了 `status_code=200` `retcode=100` 的问题。（待撤回消息在2分钟内）

## 备注
如果需要帮助测试的话我很乐意帮助你测试关于酷Q Pro相关的部分。

**Comment by stdrc** [comment]
可以看一下你的插件配置文件怎么写的吗

**Comment by SuperMarioSF** [comment]
插件配置文件是默认状态。
```ini
[general]
host=0.0.0.0
port=5700
use_http=yes
ws_host=0.0.0.0
ws_port=6700
use_ws=no
post_url=
access_token=
secret=
post_message_format=string
serve_data_files=no
update_source=https://raw.githubusercontent.com/richardchien/coolq-http-api-release/master/
update_channel=stable
auto_check_update=no
auto_perform_update=no
thread_pool_size=4
server_thread_pool_size=1
```

关于`access_token`和`secret`设置的问题，我在`demo.py`去掉了这两个参数，但故障仍然存在。

**Comment by stdrc** [comment]
Python SDK 跑起来之后，需要把对应的地址填写到插件配置的 `post_url`，比如，SDK `bot.run(host='127.0.0.1', port=8080)`，这时候 `post_url` 需要填 `http://127.0.0.1:8080/`

**Comment by stdrc** [comment]
> 但发消息的部分正常工作。只是撤回消息时遇到了 status_code=200 retcode=100 的问题。（待撤回消息在2分钟内）

撤回消息的话，发一下你是怎么调用的？

**Comment by SuperMarioSF** [comment]
> Python SDK 跑起来之后，需要把对应的地址填写到插件配置的 post_url，比如，SDK  bot.run(host='127.0.0.1', port=8080)，这时候 post_url 需要填 http://127.0.0.1:8080/

看起来是我没仔细看文档。这个问题解决了。不过建议把文档这一部分加粗一下，因为真的很容易漏掉。

**Comment by SuperMarioSF** [comment]
> 撤回消息的话，发一下你是怎么调用的？

在PyCharm的Console中测试的。
```python
PyDev console: starting.
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32

>>> from cqhttp import *
>>> bot = CQHttp(api_root='http://127.0.0.1:5700/')
>>> bot.get_group_list()
[{'group_id': 187233857, 'group_name': 'The 1stDim: VirtSpaceNavigator'}]

>>> bot.send_group_msg(group_id=187233857, message="Test message")
{'message_id': 329}

>>> bot.delete_msg(329)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python\Python3\lib\site-packages\cqhttp\__init__.py", line 39, in __call__
    raise Error(resp.status_code, data.get('retcode'))
cqhttp.Error: (200, 100)

>>> 
```

**Comment by stdrc** [comment]
这个 `bot` 对象，调用的时候，是直接通过 `__getattr__` 的键值和命名参数来构造请求路径的，所以要撤回的话，需要 `bot.delete_msg(message_id=329)`

**Comment by SuperMarioSF** [comment]
> 这个 bot 对象，调用的时候，是直接通过 __getattr__ 的键值和命名参数来构造请求路径的，所以要撤回的话，需要 bot.delete_msg(message_id=329)

好吧，把这茬给忘了...
感谢帮助。

看了你的文档最后说你现在在测试酷Q Pro上有麻烦，也许我可以在这方面帮你。我因为是需要做项目所以购买了酷Q Pro。如果可以的话我们可以交换一下联系方式，或者我也可以加入你指定的一个群组。

**Comment by stdrc** [comment]
我前段时间买了半年的 Pro，暂时可以测试，不过也欢迎加群，QQ 或者 TG 都可以，两个群互通，https://github.com/richardchien/coolq-http-api README 里面有群链接
