### ISSUE TITLE
事件上报地址无法访问

### ISSUE THREAD

**Issue by chinshin** [nonebot/python-cqhttp#5]
![pic](http://wx1.sinaimg.cn/large/831272d4ly1fo9be3a41yj21kw10mhdt.jpg)

如图，sdk也写了，配置也改了，但是事件上报时无法访问上报地址。。。

-----------------

环境：
* win server 2012r2
* 酷qAir 5.11.10A(180130)
* HTTP API 3.4.0
* cqhttp 1.1.0
* python 3.6 + requests 2.18.4

**Comment by stdrc** [comment]
你可以拿 Postman 测试一下 Python 有没有跑成功，随便发个 POST 请求到 http://127.0.0.1:8080 试试

**Comment by Mahua233** [comment]
不好意思我遇到了同样的问题 用requests发post请求返回的都是500错误
试过更改端口但是还是没有解决问题

**Comment by stdrc** [comment]
> 用requests发post请求

你 POST 发的内容是什么呢

**Comment by Mahua233** [comment]
> 你POST发的内容是什么呢

我是直接用的消息上报里的那个例子
但是依然是500

**Comment by Mahua233** [comment]
嗯刚才试着用json库转换了下发现python部分没有问题
由于我是跑在docker上的所以数据上报都是走的127.0.0.1:8080 但是依然数据传不出去

**Comment by stdrc** [comment]
Docker 里面不能直接访问容器外面，你有没有配置好

嘛花 <notifications@github.com>于2018年4月25日 周三09:49写道：

**Comment by Mahua233** [comment]
> Docker 里面不能直接访问容器外面，你有没有配置好

嗯 确实是docker的问题。

**Comment by NoneShell** [comment]
那么该如何进行配置?
