### ISSUE TITLE
传输图片

### ISSUE THREAD

**Issue by Nixiabing** [nonebot/python-cqhttp#7]
请问 在酷Q pro上可以用你的api传输图片吗？

**Comment by stdrc** [comment]
你是要发送图还是收图？

**Comment by Nixiabing** [comment]
发送图片

**Comment by stdrc** [comment]
可以的，支持文件、URL、base64 发送，https://cqhttp.cc/docs/3.4/#/CQCode?id=%E5%8F%91%E9%80%81%E7%BD%91%E7%BB%9C%E5%9B%BE%E7%89%87%E6%88%96%E8%AF%AD%E9%9F%B3
