### ISSUE TITLE
新版支持

### ISSUE THREAD

**Issue by guangzhao17** [nonebot/python-cqhttp#9]
bot.send(context, message='欢迎{}～'.format(name))
这句无法在4.4版协议上运行

**Comment by stdrc** [comment]
我测试了下，是没问题的。可以提供下你这边具体无法运行是指这句报错，还是完全没有反应，代码的上下文是什么，插件是如何配置和运行的吗

**Comment by stdrc** [comment]
你遇到的可能和 https://github.com/richardchien/python-aiocqhttp/issues/9 是同一个问题，刚刚修复了，建议尝试更新版本到 1.2.2 试试
